### ISSUE TITLE
Feature Request: Add `generateSecret` method

### ISSUE THREAD

**Issue by EastSun5566** [oslo-project/otp#2]
Hi @pilcrowOnPaper 

This library looks simple and great.

A common use case is to generate an OTP secret key for each user and then save it to the database. It would be very convenient if the library supported a method to generate secret keys. Ideally, this would include options for the number of bytes. For example:

```ts
import { generateSecret, generateTOTP } from "@oslojs/otp";

const key = generateSecret(20); // Generates a 20-byte secret key
const totp = generateTOTP(key, 30, 6);
```

What do you think?

**Comment by pilcrowonpaper** [comment]
It's just 2 lines of code so ehhhh
```ts
const secret = new Uint8Array(20);
crypto.getRandomValues(secret);
```

**Comment by EastSun5566** [comment]
Oh, I didn't realize the secret key param is a `Uint8Array`. I thought It needed to implement some encoder like base64 or something. Just curious, isn't the API too low-level? 

But now I think it isn’t needed 🙂

**Comment by pilcrowonpaper** [comment]
There's less ambiguity if you use raw bytes. Like, you don't have to guess whether the input is utf-8, hex, or base64

**Comment by BradNut** [comment]
@pilcrowOnPaper could this be added to the documentation resources?

Otherwise looking at the examples it's unclear what the `key` should be given the old docs provided a full example:
```
import { createTOTPKeyURI } from "oslo/otp";
import { HMAC } from "oslo/crypto";

const secret = await new HMAC("SHA-1").generateKey();

const issuer = "My website";
const accountName = "user@example.com";

const uri = createTOTPKeyURI(issuer, accountName, secret);
```

**Comment by KaKi87** [comment]
Also, what about a format that can be stored in a database ?
Thanks
